services:
  mcp-server:
    container_name: mcp-server
    image: ghcr.nju.edu.cn/aahl/mcp-server
    ports:
      - 8809:80
    environment:
      TZ: Asia/Shanghai
      UV_INDEX_URL: https://mirrors.ustc.edu.cn/pypi/simple
    restart: always
